export const adminDashboard = {
    total_orders: 156,
    total_revenue: 48750000,
    total_products: 24,
    average_order_value: 312500,
    today_orders: 3,
    today_revenue: 945000,
    recent_orders: [
        { id: '1', order_number: 'INV-20260601', total: 175000, status: 'delivered', customer_name: 'Rina Amelia', created_at: new Date().toISOString() },
        { id: '2', order_number: 'INV-20260602', total: 245000, status: 'shipped', customer_name: 'Budi Santoso', created_at: new Date(Date.now() - 3600000).toISOString() },
        { id: '3', order_number: 'INV-20260603', total: 89000, status: 'processing', customer_name: 'Sari Dewi', created_at: new Date(Date.now() - 7200000).toISOString() },
        { id: '4', order_number: 'INV-20260604', total: 320000, status: 'paid', customer_name: 'Dian Permata', created_at: new Date(Date.now() - 14400000).toISOString() },
        { id: '5', order_number: 'INV-20260605', total: 150000, status: 'pending', customer_name: 'Agus Wijaya', created_at: new Date(Date.now() - 28800000).toISOString() },
    ],
    low_stock: [
        { variant_id: 'v1', variant_name: 'Original 100g', sku: 'MLM-ORG-100', stock_qty: 3, threshold: 5, product_name: 'Original Popcorn' },
        { variant_id: 'v2', variant_name: 'Sweet 200g', sku: 'MLM-SWT-200', stock_qty: 0, threshold: 5, product_name: 'Sweet Popcorn' },
        { variant_id: 'v3', variant_name: 'Spicy 100g', sku: 'MLM-SPC-100', stock_qty: 2, threshold: 5, product_name: 'Spicy Popcorn' },
    ],
    orders_by_status: {
        pending: 8,
        waiting_payment: 5,
        paid: 12,
        processing: 7,
        shipped: 15,
        delivered: 98,
        cancelled: 11,
    },
    top_products: [
        { product_name: 'Original Popcorn', total_sold: 342, total_revenue: 34200000 },
        { product_name: 'Sweet Popcorn', total_sold: 287, total_revenue: 37310000 },
        { product_name: 'Spicy Popcorn', total_sold: 156, total_revenue: 17160000 },
        { product_name: 'Cheddar Popcorn', total_sold: 98, total_revenue: 12740000 },
        { product_name: 'Caramel Popcorn', total_sold: 74, total_revenue: 11100000 },
    ],
    recent_activity: [
        { id: 'a1', action: 'create', resource: 'Order', detail: 'Pesanan INV-20260605 dibuat', user_email: 'admin@malmil.id', created_at: new Date().toISOString() },
        { id: 'a2', action: 'update', resource: 'Product', detail: 'Stok Original Popcorn diperbarui', user_email: 'admin@malmil.id', created_at: new Date(Date.now() - 1800000).toISOString() },
        { id: 'a3', action: 'payment', resource: 'Order', detail: 'Pembayaran INV-20260604 dikonfirmasi', user_email: 'system@malmil.id', created_at: new Date(Date.now() - 3600000).toISOString() },
        { id: 'a4', action: 'update', resource: 'Order', detail: 'Status INV-20260603 berubah ke processing', user_email: 'admin@malmil.id', created_at: new Date(Date.now() - 7200000).toISOString() },
        { id: 'a5', action: 'create', resource: 'User', detail: 'User baru mendaftar: dian.permat@email.com', user_email: 'system@malmil.id', created_at: new Date(Date.now() - 14400000).toISOString() },
    ],
    alerts: { pending_today: 3 },
};
