import {
  Controller,
  Get,
  Post,
  Body,
  Patch,
  Param,
  Delete,
  Request,
} from '@nestjs/common';
import { DatarealService } from './datareal.service';
import { CreateDatarealDto } from './dto/create-datareal.dto';
import { UpdateDatarealDto } from './dto/update-datareal.dto';

const tables = 'm_update5s';

@Controller('datareal')
export class DatarealController {
  constructor(private readonly _service: DatarealService) {}

  @Get()
  async findAll(@Request() request) {
    return this._service.paginate(tables, [], {
      limit: request.query.limit,
      page: request.query.page,
      sort: request.query.sort,
      direction: request.query.direction,
      keyword: request.query.keyword,
      start: request.query.start,
      end: request.query.end,
      eg: request.query.noeg,
      uniq: request.query.type,
      column: [
        tables + '.id',
        tables + '.create',
        tables + '.timejob',
        tables + '.rw_volt',
        tables + '.yw_volt',
        tables + '.bw_volt',
        tables + '.ry_volt',
        tables + '.yb_volt',
        tables + '.br_volt',
        tables + '.r_ampere',
        tables + '.y_ampere',
        tables + '.b_ampere',
        tables + '.w_ampere',
        tables + '.wh_powerrecv',
        tables + '.var_recv_lag',
        tables + '.var_recv_lead',
        tables + '.var_trans_lead',
        tables + '.active_power',
        tables + '.apparent_power',
        tables + '.reactive_power',
        tables + '.power_factor',
        tables + '.freq',
        tables + '.mcbstatus_12',
        tables + '.qtyon_modbus_12',
        tables + '.qtyoff_modbus_12',
        tables + '.qty_manual_12',
        tables + '.qty_trip_12',
        tables + '.mcbstatus_13',
        tables + '.qtyon_modbus_13',
        tables + '.qtyoff_modbus_13',
        tables + '.qty_manual_13',
        tables + '.qty_trip_13',
        tables + '.mcbstatus_14',
        tables + '.qtyon_modbus_14',
        tables + '.qtyoff_modbus_14',
        tables + '.qty_manual_14',
        tables + '.qty_trip_14',
        tables + '.mcbstatus_15',
        tables + '.qtyon_modbus_15',
        tables + '.qtyoff_modbus_15',
        tables + '.qty_manual_15',
        tables + '.qty_trip_15',
        tables + '.mcbstatus_16',
        tables + '.qtyon_modbus_16',
        tables + '.qtyoff_modbus_16',
        tables + '.qty_manual_16',
        tables + '.qty_trip_16',
        tables + '.mcbstatus_17',
        tables + '.qtyon_modbus_17',
        tables + '.qtyoff_modbus_17',
        tables + '.qty_manual_17',
        tables + '.qty_trip_17',
        tables + '.mcbstatus_18',
        tables + '.qtyon_modbus_18',
        tables + '.qtyoff_modbus_18',
        tables + '.qty_manual_18',
        tables + '.qty_trip_18',
        tables + '.mcbstatus_19',
        tables + '.qtyon_modbus_19',
        tables + '.qtyoff_modbus_19',
        tables + '.qty_manual_19',
        tables + '.qty_trip_19',
        tables + '.hd1_temp',
        tables + '.hd1_hum',
        tables + '.hd2_temp',
        tables + '.hd2_hum',
        tables + '.hd3_temp',
        tables + '.hd3_hum',
        tables + '.mavstatus_1',
        tables + '.qtyon_modbus_mav1',
        tables + '.qtyoff_modbus_mav1',
        tables + '.qty_manual_mav1',
        tables + '.mavstatus_2',
        tables + '.qtyon_modbus_mav2',
        tables + '.qtyoff_modbus_mav2',
        tables + '.qty_manual_mav2',
      ],
    });
  }
}
